modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/MUYUTwilighter/BotanyPotsFix"
license = "MIT"

[[mods]]
modId = "botanypotsfix"
version = "${version}"
displayName = "Botany Pots Fix"
authors = "MUYU_Twilighter"
description = '''
Reduce lag caused by botany pots container by reducing unnecessary recipe rescanning.
'''
logoFile = "logo.png"
logoBlur = false

[[dependencies.botanypotsfix]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.botanypotsfix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.botanypotsfix]]
modId = "architectury"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.botanypotsfix]]
modId = "botanypots"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"