modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "botanypotsfix"
version = "${version}"
displayName = "Botany Pots Fix"
authors = "MUYU_Twilighter"
description = '''
Reduce lag caused by botany pots container by reducing unnecessary recipe rescanning.
'''
#logoFile = ""

[[dependencies.botanypotsfix]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.botanypotsfix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.botanypotsfix]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
